# TCL File Generated by Component Editor 21.1
# Wed May 24 15:19:40 CEST 2023
# DO NOT MODIFY


# 
# prog_gpio "prog_gpio" v1.0
#  2023.05.24.15:19:40
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module prog_gpio
# 
set_module_property DESCRIPTION ""
set_module_property NAME prog_gpio
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME prog_gpio
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL prog_gpio
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file prog_gpio.sv SYSTEM_VERILOG PATH prog_gpio.sv TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset_n reset_n Input 1


# 
# connection point pio_in
# 
add_interface pio_in conduit end
set_interface_property pio_in associatedClock clock
set_interface_property pio_in associatedReset reset
set_interface_property pio_in ENABLED true
set_interface_property pio_in EXPORT_OF ""
set_interface_property pio_in PORT_NAME_MAP ""
set_interface_property pio_in CMSIS_SVD_VARIABLES ""
set_interface_property pio_in SVD_ADDRESS_GROUP ""

add_interface_port pio_in pio_i i Input 32


# 
# connection point pio_out
# 
add_interface pio_out conduit end
set_interface_property pio_out associatedClock clock
set_interface_property pio_out associatedReset reset
set_interface_property pio_out ENABLED true
set_interface_property pio_out EXPORT_OF ""
set_interface_property pio_out PORT_NAME_MAP ""
set_interface_property pio_out CMSIS_SVD_VARIABLES ""
set_interface_property pio_out SVD_ADDRESS_GROUP ""

add_interface_port pio_out pio_o o Output 32


# 
# connection point irq_signal
# 
add_interface irq_signal interrupt end
set_interface_property irq_signal associatedAddressablePoint ""
set_interface_property irq_signal associatedClock clock
set_interface_property irq_signal associatedReset reset
set_interface_property irq_signal bridgedReceiverOffset ""
set_interface_property irq_signal bridgesToReceiver ""
set_interface_property irq_signal ENABLED true
set_interface_property irq_signal EXPORT_OF ""
set_interface_property irq_signal PORT_NAME_MAP ""
set_interface_property irq_signal CMSIS_SVD_VARIABLES ""
set_interface_property irq_signal SVD_ADDRESS_GROUP ""

add_interface_port irq_signal irq irq Output 1


# 
# connection point avalon_slave
# 
add_interface avalon_slave avalon end
set_interface_property avalon_slave addressUnits SYMBOLS
set_interface_property avalon_slave associatedClock clock
set_interface_property avalon_slave associatedReset reset
set_interface_property avalon_slave bitsPerSymbol 8
set_interface_property avalon_slave burstOnBurstBoundariesOnly false
set_interface_property avalon_slave burstcountUnits WORDS
set_interface_property avalon_slave explicitAddressSpan 0
set_interface_property avalon_slave holdTime 0
set_interface_property avalon_slave linewrapBursts false
set_interface_property avalon_slave maximumPendingReadTransactions 0
set_interface_property avalon_slave maximumPendingWriteTransactions 0
set_interface_property avalon_slave readLatency 0
set_interface_property avalon_slave readWaitTime 1
set_interface_property avalon_slave setupTime 0
set_interface_property avalon_slave timingUnits Cycles
set_interface_property avalon_slave writeWaitTime 0
set_interface_property avalon_slave ENABLED true
set_interface_property avalon_slave EXPORT_OF ""
set_interface_property avalon_slave PORT_NAME_MAP ""
set_interface_property avalon_slave CMSIS_SVD_VARIABLES ""
set_interface_property avalon_slave SVD_ADDRESS_GROUP ""

add_interface_port avalon_slave avs_write write Input 1
add_interface_port avalon_slave avs_writedata writedata Input 32
add_interface_port avalon_slave avs_address address Input 5
add_interface_port avalon_slave avs_readdata readdata Output 32
set_interface_assignment avalon_slave embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_slave embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_slave embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_slave embeddedsw.configuration.isPrintableDevice 0

