# TCL File Generated by Component Editor 21.1
# Sun Jun 18 01:33:05 CEST 2023
# DO NOT MODIFY


# 
# present "Present Cypher Module" v1.0
#  2023.06.18.01:33:05
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module present
# 
set_module_property DESCRIPTION ""
set_module_property NAME present
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME "Present Cypher Module"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL present
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file present.sv SYSTEM_VERILOG PATH ../avalon_accel/present-bloc-cipher-master/src/present.sv TOP_LEVEL_FILE
add_fileset_file present_ctrl.sv SYSTEM_VERILOG PATH ../avalon_accel/present-bloc-cipher-master/src/present_ctrl.sv
add_fileset_file present_dp.sv SYSTEM_VERILOG PATH ../avalon_accel/present-bloc-cipher-master/src/present_dp.sv
add_fileset_file present_pkg.sv SYSTEM_VERILOG PATH ../avalon_accel/present-bloc-cipher-master/src/present_pkg.sv


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clk
# 
add_interface clk clock end
set_interface_property clk clockRate 0
set_interface_property clk ENABLED true
set_interface_property clk EXPORT_OF ""
set_interface_property clk PORT_NAME_MAP ""
set_interface_property clk CMSIS_SVD_VARIABLES ""
set_interface_property clk SVD_ADDRESS_GROUP ""

add_interface_port clk clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clk
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset nrst reset Input 1

